
file:
  customer:
    file-path: src/customer_blacklist.csv

server:
  port: 9999

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: local
file:
  voucher:
    file-path: src/voucher_memory.csv

---

spring:
  config:
    activate:
      on-profile: jdbc
  datasource:
    url: jdbc:mysql://localhost/voucher_app?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root1234!
  mvc:
    hidden-method:
      filter:
        enabled: true

file:
  voucher:
    file-path: src/voucher_memory.csv