
file:
  customer:
    file-path: src/customer_blacklist.csv

spring:
  datasource:
    url: jdbc:mysql://localhost/voucher_app
    username: root
    password: root1234!
#    url: ENC(f93Xh1npbmfdq5mbBgh77VTmbM8+hNQ6esK0HoD4kBC4DrqqcXem2wy09B/+UCSO)
#    username: ENC(eHxnuZNylJtbhVIBj1nVUA==)
#    password: ENC(GPnl+ytq8YcrZPiJ+YegDBJza6x9F8Am)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: local
file:
  voucher:
    file-path: src/voucher_memory.csv

---


spring:
  config:
    activate:
      on-profile: jdbc
file:
  voucher:
    file-path: src/voucher_memory.csv
